from django.utils.translation import ugettext_lazy as _

CAUSE_REGION_CITY = 1
CAUSE_REGION_COUNTY = 2
CAUSE_REGION_STATE = 3
CAUSE_REGION_NATIONAL = 4
CAUSE_REGION_CHOICES = (
	(CAUSE_REGION_CITY, _(u'City')),
	(CAUSE_REGION_COUNTY, _(u'County')),
	(CAUSE_REGION_STATE, _(u'State')),
	(CAUSE_REGION_NATIONAL, _(u'National')),
)

CAUSE_TYPE_FISCAL = 1
CAUSE_TYPE_SOCIAL = 2
CAUSE_TYPE_OTHER = 3
CAUSE_TYPE_CHOICES = (
	(CAUSE_TYPE_FISCAL, _(u'Fiscal')),
	(CAUSE_TYPE_SOCIAL, _(u'Social')),
	(CAUSE_TYPE_OTHER, _(u'Other')),
)

CAUSE_STATUS_OPEN = 1
CAUSE_STATUS_ACCEPTED = 2
CAUSE_STATUS_DECLINED = 3
CAUSE_STATUS_CLOSED = 4
CAUSE_STATUS_CHOICES = (
	(CAUSE_STATUS_OPEN, _(u'Open')),
	(CAUSE_STATUS_ACCEPTED, _(u'Accepted')),
	(CAUSE_STATUS_DECLINED, _(u'Declined')),
	(CAUSE_STATUS_CLOSED, _(u'Closed')),
)

PLEDGE_PAYMENT_VISA = 1
PLEDGE_PAYMENT_MASTERCARD = 2
PLEDGE_PAYMENT_PAYPAL = 3
PLEDGE_PAYMENT_AMAZON = 4
PLEDGE_PAYMENT_GOOGLEWALLET = 5
PLEDGE_PAYMENT_CHOICES = (
	(PLEDGE_PAYMENT_VISA, _(u'Visa')),
	(PLEDGE_PAYMENT_MASTERCARD, _(u'MasterCard')),
	(PLEDGE_PAYMENT_PAYPAL, _(u'PayPal')),
	(PLEDGE_PAYMENT_AMAZON, _(u'Amazon')),
	(PLEDGE_PAYMENT_GOOGLEWALLET, _(u'Google Wallet')),
)

PLEDGE_STATUS_PENDING = 1
PLEDGE_STATUS_VERIFIED = 2
PLEDGE_STATUS_PROCESSED = 3
PLEDGE_STATUS_DECLINED = 4
PLEDGE_STATUS_CHOICES = (
	(PLEDGE_STATUS_PENDING, _(u'Pending')),
	(PLEDGE_STATUS_VERIFIED, _(u'Verified')),
	(PLEDGE_STATUS_PROCESSED, _(u'Processed')),
	(PLEDGE_STATUS_DECLINED, _(u'Declined')),
)